const terror = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.'
    },
    body: {
      items: {
        item: [
          {
            actRmks:
              '일반전화기·휴대폰을 이용하여 국번 없이 112(경찰청) 신고번호만 눌러 통화합니다.',
            contentsType: 1,
            mainOrd: 70,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022007,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '신고요령',
            subOrd: 1
          },
          {
            actRmks:
              '공중전화기를 이용할 시에는 동전이나 전화카드가 없어도 빨간색 긴급버튼을 누른 후 신고번호를 입력하면 통화가 됩니다.',
            contentsType: 1,
            mainOrd: 70,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022007,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '신고요령',
            subOrd: 2
          },
          {
            actRmks:
              '통화가 되면 우선 자신의 이름, 소속(직업), 현재 위치를 밝히고 의심스럽게 생각되는 내용과 이유를 가급적 6하 원칙에 따라 자세히 신고하는 것이 좋습니다.',
            contentsType: 1,
            mainOrd: 70,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022007,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '신고요령',
            subOrd: 3
          },
          {
            actRmks:
              '거동 수상자를 신고할 때는 옷차림, 외견상 특이점, 행동상 수상한 점을 마음속으로 정리해서 신고해 주십시오.',
            contentsType: 1,
            mainOrd: 70,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022007,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '신고요령',
            subOrd: 4
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 70,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022007,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '신고요령',
            subOrd: 5
          },
          {
            actRmks: '【대피 방법】',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 1
          },
          {
            actRmks:
              '우선적으로 제3자에게도 상황전파 → 관계기관 신고 → 안전지역으로 대피하고, 피해 지역 탈출 시 당황하지 말고 침착하고 질서있게 비상구를 통해 신속히 지상으로 대피합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 2
          },
          {
            actRmks:
              '재난사고를 최초로 발견한 자는 다른 사람에게도 신속히 상황을 전파한 후 가까운 행정기관 경찰서, 소방서 등에 신고합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '가급적 지상으로 대피하여야 하지만 내려가는 계단이 막혔을 때는 옥상으로 탈출하여 외부의 도움을 요청합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 4
          },
          {
            actRmks:
              '비상계단을 내려갈 땐 불이 난 곳의 반대방향인지 확인하고, 갇히면 빠져 나오기 힘들기 때문에 화장실이나 막다른 곳으로 가지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 5
          },
          {
            actRmks:
              '아래층에 불이나 1층으로 내려갈 수 없으면 옥상이나 창가 등 숨을 쉴 수 있는 곳으로 대피해 구조를 기다립니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 6
          },
          {
            actRmks:
              '지상에 도착하더라도 건물붕괴 후에 폭풍 등을 감안, 안전을 위해 견고한 외벽을 따라 대피하되 건물높이 2배 이상의 거리 밖으로 벗어나야 합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 7
          },
          {
            actRmks:
              '차량을 이용하여 대피하려 주차장으로 가지 말고 바로 지상으로 대피하여야 합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 8
          },
          {
            actRmks:
              '유도요원이 있을 경우 유도에 따라 대피하여야 하며, 사태 수습 복구요원이 도착하였을 경우 사상자 위치를 안내하고 복구요원의 신속한 진입에 방해가 되지 않도록 길을 비켜줍니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 9
          },
          {
            actRmks: '【유의사항】',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 10
          },
          {
            actRmks:
              '대형건물에 화재가 났을 때는 정전으로 엘리베이터가 작동을 멈추기 때문에 엘리베이터를 타는 것은 위험하므로 비상계단 등을 이용합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 11
          },
          {
            actRmks:
              '다급하다고 하여 창문으로 무작정 뛰어 내리지 말고, 이동시에는 벽돌·유리 등 파괴된 건축물 파편으로 인한 안전사고 위험에 유의합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 12
          },
          {
            actRmks:
              '사무실 문밖에서 "불이야"하는 소리가 들린다고 해서 문을 확 열어서는 안되며, 몸을 문 뒤로 천천히 열어야 합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 13
          },
          {
            actRmks: '전기화재는 감전위험이 있기 때문에 물을 쓰면 안됩니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 14
          },
          {
            actRmks:
              '특히, 문의 손잡이가 뜨거울 때는 복도의 불길이 세다는 증거이므로 문을 열면 안되며, 이럴 경우에는 문틈을 막고 문 주변에 물을 뿌린 다음 창문을 열고 구조를 기다려야 합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 15
          },
          {
            actRmks:
              '복도를 빠져나갈 때에는 유독가스가 차 있을 수도 있게 때문에 함부로 뛰어서는 안됩니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 16
          },
          {
            actRmks:
              '가스유출시 천장부터 차기 때문에 납작 엎드려서 젖은 수건으로 코와 입을 막고 기어서 대피합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 17
          },
          {
            actRmks:
              '옷에 불이 붙으면 이리저리 도망다니지 말고 이불 담요 등으로 감싸거나 바닥에 누워 뒹굴면서 손으로 두들겨 끕니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 18
          },
          {
            actRmks: '귀중품에 연연하지 말고 대피를 최우선으로 하여야 합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 19
          },
          {
            actRmks:
              '개인행동은 자제하고 항상 2인 이상 안전지역으로 이동하고 만약 노약자, 어린이 등이 있을 경우 함께 대피합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 20
          },
          {
            actRmks:
              '유언비어에 현혹되지 말고 유언비어로 인한 공포분위기 조성에 침착하게 대처하고 정부의 지시에 따라 신속하게 행동합니다.',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 21
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 80,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022008,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '대형, 고층건물 재난시 행동요령',
            subOrd: 22
          },
          {
            actRmks:
              '주변 사람들에게 알리면서 폭탄이 발견된 지점의 반대방향 계단으로 즉시 대피합니다. 이때 엘리베이터는 절대 이용하지 말아야 하며 계단의 한쪽만을 이용(우측통행)하여 폭발물 처리팀이나 소방관들이 이동할 수 있도록 해야 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 1
          },
          {
            actRmks:
              '휴대전화·라디오·무전기 등은 기폭장치를 작동시킬 수 있으므로 사용하지 않도록 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 2
          },
          {
            actRmks: '대피 후에는 안전거리(붕괴: 건물높이 이상, 폭발: 500m이상) 밖으로 이동합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '대피경로에도 제2의 폭발물이 설치되어 있을 수 있으므로 주의하면서 대피해야 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 4
          },
          {
            actRmks: '대피도중 폭발물이 터지면 비산·낙하물을 피하는데 유의해야 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 5
          },
          {
            actRmks:
              '대피시에는 신체를 보호하기 위해서 즉시 바닥에 엎드려 양팔과 팔꿈치를 옆구리에 붙이고 손으로 귀와 머리를 감싸야 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 6
          },
          {
            actRmks:
              '강당, 로비 등 기둥 간격이 넓은 곳은 붕괴위험이 높으므로 이런 곳에서 벗어나야 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 7
          },
          {
            actRmks:
              '유리·간판·전등 등의 비산·낙하물이 없을 만한 곳이나 책상 등의 아래에 피신해야 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 8
          },
          {
            actRmks: '휴대전화를 켜 놓아 붕괴·매몰시 자신의 위치가 알려질 수 있도록 합니다.',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 9
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 90,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022009,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '폭발물 발견시 행동요령',
            subOrd: 10
          },
          {
            actRmks:
              '대피시 방독면이나, 물수건, 각종 마스크, 비닐 등을 이용해서 호흡기를 보호하고, 피부의 노출을 최대한 방지하여야 합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 1
          },
          {
            actRmks:
              '사고지점 인근에서는 바람이 불어오는 방향으로 이동하고 멀리 떨어진 지역에서는 바람이 불어오는 직각 방향으로 대피합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 2
          },
          {
            actRmks: '즉시 가까이 있는 사람에게 알려주고 경찰서(112)나 소방서(119)에 신고합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '지하철역이나 백화점 등 밀폐된 시설에서는 겉옷이나 손수건 등을 사용하여 코와 입을 막고 실외로 신속히 대피합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 4
          },
          {
            actRmks:
              '대피시 현장의 안내 유도요원이나 종사자의 통제에 따라 질서 정연히 대피해야 합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 5
          },
          {
            actRmks: '야외에서는 고층건물이나 고지대로 대피합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 6
          },
          {
            actRmks:
              '오염된 지역에서는 식수나 음식물은 절대로 먹지 말고, 오염된 물체를 맨손으로 만지지 않도록 주의를 기울입니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 7
          },
          {
            actRmks: '대피 후 몸에 이상이 있을 경우 이웃에 알려 구조 요청을 합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 8
          },
          {
            actRmks: '주택가, 저층건물, 야외에 있을 경우 미리 알려둔 대피장소로 신속히 이동합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 9
          },
          {
            actRmks:
              '이러한 예방조치를 취했다 하더라도 오염환자가 발생했을 경우 병·의원에 신속히 이동하여 전문치료를 받아야 합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 10
          },
          {
            actRmks: '※ 독가스별 응급처치요령',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 11
          },
          {
            actRmks:
              '신경작용제: 해독제킷(아드로핀, 옥심주사)을 10분 간격으로 3번 주사하고, 호흡이 곤란한 경우는 인공호흡을 실시하고 병원으로 긴급 후송합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 12
          },
          {
            actRmks:
              '수포작용제: 따뜻한 비눗물로 세척하되 눈은 깨끗한 물로 씻고, 피부제독킷(KM258, KM 258A1) 등을 이용하여 제독합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 13
          },
          {
            actRmks:
              '질식/혈액작용제: 체온을 유지하도록 따뜻한 곳으로 이동하여 따뜻한 물을 마시도록 하고, 호흡이 곤란할 경우 인공호흡 조치를 취한 후 병원으로 신속히 후송하여야 합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 14
          },
          {
            actRmks:
              '염소가스: 물로 15분 이상 피부를 세척하되 눈 부위는 3% 정도의 식염수로 씻고, 소금물로 입가심을 하거나 버터를 넣은 커피를 마십니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 15
          },
          {
            actRmks:
              '암모니아가스: 레몬주스 또는 0.5%의 구연산수를 마시도록 하고, 피부는 2% 붕산수로 세척을 하되 10분마다 5분간 세척해야 합니다.',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 16
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 100,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022010,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화학테러(독가스 등) 발생시 행동요령',
            subOrd: 17
          },
          {
            actRmks: '건드리지 말고 그대로 두고 당국에 신고합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 1
          },
          {
            actRmks:
              '실내에 있을 경우에는 창문과 문을 모두 닫고 주변 사람들을 대피시키며 에어컨·환기시설 등을 모두 꺼야 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 2
          },
          {
            actRmks:
              '의심 물질이 날릴 염려가 있을 경우는 옷, 신문지 등으로 조심스럽게 덮어 두어야 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '손수건·휴지 등을 여러 겹으로 겹쳐 코와 입을 가리고 호흡하면서 즉시 그 자리를 피해야 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 4
          },
          {
            actRmks: '대피 후에는 즉시 비눗물 샤워로 오염물질이 신체에 부착되지 않도록 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 5
          },
          {
            actRmks: '입었던 옷, 신발 등은 소독 후 폐기하여야 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 6
          },
          {
            actRmks:
              '생물 테러의 증상은 고열·구역질·복통·설사·콧물·인후염·피부 발진 및 피부염·안구충혈·무기력증 등 여러 가지가 있으나 즉시 나타나지 않고 시일을 두고 나타나므로 조기에 대처하는 것이 가장 중요합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 7
          },
          {
            actRmks:
              '테러에 사용되는 물질들은 이미 치료제가 개발되어 있기 때문에 조기에 치료하면 치유가 가능하므로 침착하게 행동하도록 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 8
          },
          {
            actRmks:
              '생물테러 징후가 보이면 방송이나 보건 당국의 인터넷 홈페이지를 통해 관련 정보를 수시로 파악하도록 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 9
          },
          {
            actRmks:
              '인근지역에 생물테러 경보가 발령되었을 때, 질병의 확산을 방지하고자 보건 및 청결 상태 등을 유지하고 보건당국의 지시를 따라야 합니다.',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 10
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 110,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022011,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '생물테러 발생시 행동요령',
            subOrd: 11
          },
          {
            actRmks:
              '방사능 누출은 사람의 오감으로는 감지가 불가능하며 경찰이나 소방서에서 3~5분간의 사이렌 파상신호로 방사능 누출 비상연락을 할 시에는 가급적 외출을 삼가고 집안이나 콘크리트 건물 내 안전한 장소로 대피해야 합니다.',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 1
          },
          {
            actRmks:
              '대피시 사무실이나 집은 반드시 잠그고 흰 수건이나 의류를 눈에 잘 띄는 곳에 걸어 두어 대피 완료 표시를 합니다.',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 2
          },
          {
            actRmks:
              '대피장소는 대개 지하실이나 건물의 중앙이 효과적인데 모든 창문과 출입문은 잠그며 문틈은 젖은 신문지나 헝겊 등으로 반드시 밀폐하여야 합니다.',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '환기 및 공기 정화기의 팬은 끄고, 방사선 물질이 통과한 후에는 풍향의 반대쪽 문을 열어두어야 합니다.',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 4
          },
          {
            actRmks: '라디오, TV 등을 통한 정부지시에 따라 행동합니다.',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 5
          },
          {
            actRmks:
              '건물 내 방사능 유출 경고가 있으면 방독면을 쓰거나 코와 입을 손수건 또는 휴지 등으로 가리고 방사능에 오염되지 않은 건물 안으로 대피합니다.',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 6
          },
          {
            actRmks:
              '실내에 있을 때는 건물이 방사능에 오염되었는지를 확인하고 오염되지 않았다면 바깥으로 나오지 말고 그대로 있는 것이 좋습니다.',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 7
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 120,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022012,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '방사능 테러 발생시 행동요령',
            subOrd: 8
          },
          {
            actRmks: '경보기를 눌러 주변 사람들에게 신속히 알립니다.',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 1
          },
          {
            actRmks: '주변에 있는 손전등을 찾아 들도록 합니다.\\',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 2
          },
          {
            actRmks: '손수건 등을 물에 적셔 코와 입을 가립니다.',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '화염·연기가 적은 피난통로를 선택하여 대피합니다. 이 때 엘리베이터는 이용하지 말아야 하며 문을 열 때에는 손으로 짚어 뜨거우면 열지 말고 다른 곳으로 대피해야 합니다.',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 4
          },
          {
            actRmks:
              '피난통로의 한쪽을 이용(우측통행)하여 구조·소방대원이 이동할 수 있도록 해야 합니다.',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 5
          },
          {
            actRmks: '대피할 때에는 자세를 낮추고 벽 가까이로 질서 있게 대피합니다.',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 6
          },
          {
            actRmks: '귀중품 등을 챙기려고 지체하지 말고 즉시 대피해야 합니다.',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 7
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 130,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022013,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '화재 발생시 행동요령',
            subOrd: 8
          },
          {
            actRmks: '즉시 바닥에 엎드리거나 자세를 낮추어 몸을 숨길 수 있는 곳으로 이동합니다.',
            contentsType: 1,
            mainOrd: 140,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022014,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '총격현장 행동요령',
            subOrd: 1
          },
          {
            actRmks:
              '경찰·경비원의 대응사격에 방해가 되지 않도록 경찰·경비원의 지시에 따라야 합니다.',
            contentsType: 1,
            mainOrd: 140,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022014,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '총격현장 행동요령',
            subOrd: 2
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 140,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022014,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '총격현장 행동요령',
            subOrd: 3
          },
          {
            actRmks: '불필요한 활동이나 고함으로 체력을 소모하지 않도록 합니다.',
            contentsType: 1,
            mainOrd: 150,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022015,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '매몰, 붕괴시 행동요령',
            subOrd: 1
          },
          {
            actRmks: '입과 코를 옷이나 천으로 가려서 먼지 흡입을 최소화 합니다.',
            contentsType: 1,
            mainOrd: 150,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022015,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '매몰, 붕괴시 행동요령',
            subOrd: 2
          },
          {
            actRmks: '규칙적으로 벽, 파이프 등을 두드려 자신의 위치를 알립니다.',
            contentsType: 1,
            mainOrd: 150,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022015,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '매몰, 붕괴시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '휴대전화의 전파는 매몰자 탐색에 도움이 될 수 있기 때문에 전원은 규칙적으로 일정시간만 켜서 배터리를 절약해야 합니다.',
            contentsType: 1,
            mainOrd: 150,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022015,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '매몰, 붕괴시 행동요령',
            subOrd: 4
          },
          {
            actRmks:
              '구조될 수 있다는 희망을 가지고 물과 음식을 찾아 먹으면서 체온 유지에 힘써야 합니다.',
            contentsType: 1,
            mainOrd: 150,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022015,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '매몰, 붕괴시 행동요령',
            subOrd: 5
          },
          {
            actRmks:
              '2차 붕괴나 낙하물에 대비하여 단단한 테이블 밑이나 창문이 없는 단단한 벽체 옆에서 기다리도록 합니다.',
            contentsType: 1,
            mainOrd: 150,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022015,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '매몰, 붕괴시 행동요령',
            subOrd: 6
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 150,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022015,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '매몰, 붕괴시 행동요령',
            subOrd: 7
          },
          {
            actRmks:
              '만일 인질로 억류되었거나 납치 감금을 당했다면 저항하지 말고 순순히 하라는 대로 응하고 급작스러운 행동을 피해야 합니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 1
          },
          {
            actRmks: '탈출 성공 가능성이 낮다고 판단될 때는, 탈출을 시도하지 않는 것이 좋습니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 2
          },
          {
            actRmks:
              '납치된 사람이 다수일 때는 눈에 잘 띄지 않도록 처신하고, 납치범에게 위협적인 인상을 쓰는 것은 금물이며, 납치범과 눈이 마주치는 것도 피해야 합니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 3
          },
          {
            actRmks:
              '납치범들이 무엇인가를 물어올 때는 답은 되도록 짧게 자연스러운 자세로 대답하고, 화를 내서는 안 됩니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 4
          },
          {
            actRmks:
              '납치범이 무엇인가 지시할 때는 공손하게 순응하고, 그들을 자극할 수 있는 언행을 삼가며, 육성녹음을 요구할 때 기꺼이 응하도록 합니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 5
          },
          {
            actRmks:
              '어떠한 상황에서건 외부에서 구출을 위한 모든 수단이 동원되고 있으므로 자제력을 잃지 말고 절망감을 느껴서는 안되며, 탈출로 등 자신이 유리하게 활용할 수 있는 여건을 파악해야 합니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 6
          },
          {
            actRmks:
              '건강 유지를 위해 계속 운동하고, 주는 것은 모두 먹고, 몸이 아플 때는 약을 요구하도록 합니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 7
          },
          {
            actRmks:
              '치범과 대화를 할 수 있다면 그들과 대화를 하는 것이 좋으며 우호적 관계를 유지하도록 노력해야 합니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 8
          },
          {
            actRmks:
              '석방시기가 임박할 때도 자제력을 잃지 않도록 하며 갑작스러운 태도 변화를 보여서도 안 됩니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 9
          },
          {
            actRmks: '구출작전이 전개될 때는 즉시 엎드려야 합니다.',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 10
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 160,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022016,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '억류, 납치시 행동요령',
            subOrd: 11
          },
          {
            actRmks: '【외관】',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 1
          },
          {
            actRmks:
              '마스크나 수염 등으로 얼굴을 가리거나 모자 또는 짙은 색깔의 안경을 착용한 사람',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 2
          },
          {
            actRmks:
              '겉옷 안에 불분명한 물체 등을 넣은 것으로 보여 지나치게 배부분이 튀어나왔거나, 계절에 맞지 않는 두껍고 긴 상의를 입어 땀을 많이 흘리며 눈초리가 불안한 사람',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 3
          },
          {
            actRmks: '【행동】',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 4
          },
          {
            actRmks:
              '다중이용시설 쓰레기통이나 화장실 등에 평범하게 보이는 가방이나 봉지를 실수인 척 방치하고 현장을 급히 이탈하는 사람 ? 물건을 빠뜨렸다고 알려주고 이후 행동 주시',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 5
          },
          {
            actRmks:
              '다중이용시설 인근에 오토바이나 차량을 방치하고 급히 이탈 ? 차량 이동 요구, 불심검문 등 조치',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 6
          },
          {
            actRmks:
              '경찰 등 보안요원들을 의도적으로 피하거나 갑자기 뛰는 등 비정상적인 행동을 보이는 사람',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 7
          },
          {
            actRmks: '국적이나 숙소를 묻는 질문에 거부감을 표시',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 8
          },
          {
            actRmks:
              '젊은 남녀가 군중 속에서 일행이 어니면서도 복장과 행동을 맞추어 합류하려 시도하는 행동',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 9
          },
          {
            actRmks: '가방이나 의복 속에서 전선이나 전기장치가 보일 경우',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 10
          },
          {
            actRmks: '의도적으로 보안요원들에게서 멀리 떨어지려고 시도',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 11
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 180,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017001,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 12
          },
          {
            actRmks: '【차량 이용 테러】',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 12
          },
          {
            actRmks: '1. 운전자',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 13
          },
          {
            actRmks: '운전자가 변덕스런 운전을 할 때(천천히 또는 빨리)',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 14
          },
          {
            actRmks: '정지명령을 무시하고 검문소 우회를 시도할 때',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 15
          },
          {
            actRmks: '불안한 모습이나 비정상적인 언어를 구사하는 경우',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 16
          },
          {
            actRmks: '트럭 또는 장비를 서투르게 다루는 행위',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 17
          },
          {
            actRmks: '2. 차량',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 18
          },
          {
            actRmks: '차량바퀴가 눈에 띄게 내려 않았을 때',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 19
          },
          {
            actRmks: '창문이 어둡거나 가려져 있을 때',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 20
          },
          {
            actRmks: '차량안에 의심스런 물건이 실려 있을 경우',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 21
          },
          {
            actRmks: '차량에 보조 안테나가 달려있을 경우',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 22
          },
          {
            actRmks: '주차할 장소가 아닌 곳에 방치되듯이 주차되어 있는 경우',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 23
          },
          {
            actRmks: '앞뒤 번호판이 다르거나 미등록 임시번호판 부착',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 24
          },
          {
            actRmks: '【폭탄?화생방 물질 이용 테러】',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 25
          },
          {
            actRmks: '1. 우편물 테러',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 26
          },
          {
            actRmks: '겉봉에 "본인개봉요망", "비공개" 등 표시',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 27
          },
          {
            actRmks: '우표를 규정요금 보다 과다하게 부착',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 28
          },
          {
            actRmks: '발신처 불명의 해외 항공·특수우편물',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 29
          },
          {
            actRmks: '테이프·포장 줄 등을 과다 사용하여 봉인',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 30
          },
          {
            actRmks: '조잡한 필체로 주소 기재',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 31
          },
          {
            actRmks: '반송 주소가 없음(보낸 사람 불명)',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 32
          },
          {
            actRmks: '발신 우체국인과 발신주소가 다르게 표시',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 33
          },
          {
            actRmks: '수취인이 불명확하거나 직책만 표시',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 34
          },
          {
            actRmks: '회사 이름만 기재되고 직책·이름을 잘못 기재',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 35
          },
          {
            actRmks: '직접 배달하거나 낯선 사람이 전달',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 36
          },
          {
            actRmks: '포장 내부 일부분이 유난히 단단',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 37
          },
          {
            actRmks: '주변이 찌그러졌거나 표면이 울퉁불퉁',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 38
          },
          {
            actRmks: '포장이 매끄럽지 못하고 불균형',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 39
          },
          {
            actRmks: '2. 사제폭발물',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 40
          },
          {
            actRmks: '건전지·전선 등의 내용물 동봉',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 41
          },
          {
            actRmks: '포장 외부로 얇은 줄이나 전선 노출',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 42
          },
          {
            actRmks: '포장지가 기름·얼룩 등 이물질 오염',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 43
          },
          {
            actRmks: '우편물 크기에 비해 무거운 중량',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 44
          },
          {
            actRmks: '3. 화학테러 물질',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 45
          },
          {
            actRmks: '아몬드·복숭아·마른 풀 등 특이한 냄새',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 46
          },
          {
            actRmks: '겉봉투에 얼룩이나 탄 흔적',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 47
          },
          {
            actRmks: '취급 때 눈물이 나거나 피부가 따가운 느낌',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 48
          },
          {
            actRmks: '유리병 등 유독물을 담을 수 있는 용기 발견',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 49
          },
          {
            actRmks: '4. 생물테러 물질',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 50
          },
          {
            actRmks: '말랑말랑한 가루가 만져지는 봉투',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 51
          },
          {
            actRmks: '포장지에 백색 가루 흔적 등 발견',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 52
          },
          {
            actRmks: '가루가 새지 않게 비닐 등으로 이중 포장',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 53
          },
          {
            actRmks: '5. 방사능 테러 물질',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 54
          },
          {
            actRmks: '우편물에 정체불명의 금속물질 포장',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 55
          },
          {
            actRmks: '만졌을 때 주위보다 뜨거운 열기 감지',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 56
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 190,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017002,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 57
          },
          {
            actRmks: '【최초 발견시】',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 57
          },
          {
            actRmks: '냄새를 맡거나 맨손으로 만지지 않습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 58
          },
          {
            actRmks: '조심스럽게 우편물을 내려놓습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 59
          },
          {
            actRmks: '던지거나 흔드는 등 충격을 주지 않습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 60
          },
          {
            actRmks: '라이터 등 가연성 물질을 가까이하지 않습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 61
          },
          {
            actRmks: '외부로 노출된 얇은 줄이나 전선을 잡아당기거나 자르지 않습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 62
          },
          {
            actRmks: '휴대전화 등 전자파 발생방지장치를 사용하지 않습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 63
          },
          {
            actRmks:
              '백색 가루 등 화생방물질로 의심되면 외부로 누출을 방지하고자 비닐 등에 넣습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 64
          },
          {
            actRmks: '우편물 보관 장소를 떠납니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 65
          },
          {
            actRmks: '인근 경찰서나 112에 신고합니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 66
          },
          {
            actRmks: '비눗물을 사용하여 손을 깨끗이 씻습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 67
          },
          {
            actRmks: '【우편물 등 개봉시】',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 68
          },
          {
            actRmks:
              '사제폭탄으로 추정되는 우편물일 경우 즉시 그 장소를 떠나고 인근경찰서 등 관계 당국에 신고합니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 69
          },
          {
            actRmks:
              '총기 등 동봉 우편물일 경우 만지지 말고 원상태로 보존한 후 인근 경찰서나 소방서 등에 신고합니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 70
          },
          {
            actRmks:
              '화생방 의심 물질이 있는 우편물일 경우 접촉하지 말고 수건 등으로 코, 입을 막은 뒤 창과 문을 닫고 우편물 개봉장소를 즉시 떠납니다. 화생방물질이 묻었으면 신속히 옷을 벗고 흐르는 물에 씻되 피부를 문지르거나 긁지 않습니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 71
          },
          {
            actRmks:
              '오염 확산을 방지하기 위해 다른 사람과 접촉을 피하고 인근 경찰관서 및 화생방 전문기관에 신고합니다.',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 72
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 200,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017003,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 73
          },
          {
            actRmks: '【공항】',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 73
          },
          {
            actRmks:
              '항공권 발급 및 입출국 수속시 직원과 눈을 마주치지 않으려 하거나 대화를 기피하는 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 74
          },
          {
            actRmks:
              '신규·임시 발급·재발급 여권을 소지하고 있는 사람 ※ 첫 검색 대상인 신규 여권과 위조가 용이한 임시여권 소지자에 대해서는 상대적으로 철저한 검색이 필요',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 75
          },
          {
            actRmks: '타 여행객에 접근하여 가방·서류(봉투) 등을 건네는 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 76
          },
          {
            actRmks:
              '여권상 여행국 출입국 날짜·횟수 등에 대해 전혀 기억을 하지 못하거나 반대로 수년 전 기록된 출입국 날짜를 정확하게 외우고 있는 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 77
          },
          {
            actRmks:
              '중동·북부아프리카·동남아·서남아 등 국제테러조직 활동지역 여권을 소지하고 있는 자',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 78
          },
          {
            actRmks:
              '여권기재 직업 관련 전문용어에 대해 무지하거나 소지자의 직업·연령 등이 기재사항과 불일치하는 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 79
          },
          {
            actRmks:
              '실물과 사진이 현저히 다르거나 유럽·영국·미국·호주 여권을 사용하면서도 영어가 서툰 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 80
          },
          {
            actRmks: '【호텔】',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 81
          },
          {
            actRmks: '외출시간이 극히 적으며, 대부분 방안에 머물러 있는 자',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 82
          },
          {
            actRmks:
              '여권 기재 직업 관련 전문용어에 대해 무지하거나 소지자 직업·연령 등이 기재사항과 불일치하는 자',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 83
          },
          {
            actRmks:
              '처음 방문하는 지역에서 렌트 차량이 아닌 일반차량, 픽업트럭 등 사용하거나, 차량을 렌트하였음에도 이용치 않고 장기간 방치하는 경우',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 84
          },
          {
            actRmks:
              '손가방 등 수하물을 객실로 옮겨주겠다는 직원 제의에 과민반응하며 수하물에 집착하거나 화를 내는 자',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 85
          },
          {
            actRmks:
              '장기간 청소를 거부하고 룸서비스도 문밖에서만 받는 등 외부인의 방 출입을 철저히 차단하는 자',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 86
          },
          {
            actRmks: '【철도】',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 87
          },
          {
            actRmks: '승차권 발급시 생각 없이 목적지를 번복·변경하는 자',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 88
          },
          {
            actRmks:
              '성인, 특히 외국인이 철로 주변을 서성거리며 사진을 찍거나 줄자 등을 이용해 계측하는 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 89
          },
          {
            actRmks: '물품보관함의 물품 영치자와 회수자가 다른 경우',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 90
          },
          {
            actRmks: '【백화점】',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 91
          },
          {
            actRmks:
              '국제테러조직 활동 근거지인 중동·북부아프리카·동남아·서남아 지역 국가 신용카드나 신분증 소지자',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 92
          },
          {
            actRmks:
              '화장실·휴게실·쓰레기통 등에 가방 등 물품을 방치하거나 출입구 등 왕래가 많은 곳에 차량을 주차한 후 황급히 떠나는 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 93
          },
          {
            actRmks: '【음식점·유흥주점·나이트클럽】',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 94
          },
          {
            actRmks:
              '술을 주문하지 않거나 주문해 놓고도 거의 마시지 않은 채 구석자리에 앉아 주위를 유심히 살피는 외국인',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 95
          },
          {
            actRmks:
              '화장실·휴게실·쓰레기통에 가방 등 물품을 방치하거나 출입구 등 왕래가 많은 곳에 차량을 주차한 후 황급히 떠나는 사람',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 96
          },
          {
            actRmks: '자료제공: 경찰청',
            contentsType: 1,
            mainOrd: 210,
            safetyCate1: 2,
            safetyCate2: 2022,
            safetyCate3: 2022017,
            safetyCate4: 2022017004,
            safetyCateNm1: '사회재난',
            safetyCateNm2: '테러',
            safetyCateNm3: '테러범·의심물체 등 식별요령',
            subOrd: 97
          }
        ]
      },
      numOfRows: 10,
      pageNo: 1,
      totalCount: 202
    }
  }
}
export default terror
