const tranportMachineAcc = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.'
    },
    body: {
      items: {
        item: [
          {
            actRmks:
              '우리는 일상생활 중 아파트와 빌딩,병원,백화점 등에서 승강기를 많이 이용합니다. 이제 승강기 없는 생활은 상상할 수 없을 만큼 그 중요성이 갈수록 커지고 있습니다. 이토록 중요한 승강기를 올바로 이용 하지 않으면 고장이나 사고가 발생할 수 있기 때문에 다음과 같은 이용 수칙을 꼭 지켜줄 것을 당부하고 있습니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 1
          },
          {
            actRmks: '정원 및 적재하중의 초과는 고장이나 사고의 원인이 되므로 엄수하여야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 2
          },
          {
            actRmks: '조작반의 인터폰 및 비상정지스위치 등을 장난하지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 3
          },
          {
            actRmks: '승강기 내에서 뛰거나 구르는 등의 행동을 하지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 4
          },
          {
            actRmks: '어린이와 노약자는 가급적 보호자와 함께 이용하도록 하여야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 5
          },
          {
            actRmks: '문턱에 이물질이 끼거나 틈새에 물이 들어 가지 않도록 해야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 6
          },
          {
            actRmks: '화재 시에는 승강기를 타지 말고 비상계단을 이용해야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 7
          },
          {
            actRmks: '도어개폐기 출입문에 기대면 손이나 옷자락이 딸려 들어가므로 조심해야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 8
          },
          {
            contentsType: 2,
            contentsUrl:
              'http://mepv2.safekorea.go.kr/mdbs_html/images/mobileWeb/hElevator/hElevator_icon_01.png',
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 9
          },
          {
            actRmks:
              '정전이나 고장 등으로 승강기 안에 갇히면 인터폰으로 구조를 요청하고 보수업체, 119구조대 등의 구조를 받을 때까지 침착하게 기다립시다',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 이용',
            subOrd: 10
          },
          {
            actRmks:
              '승강기는 많은 사람이 이용하는 공동 시설물이므로 올바른 이용수칙과 함께 에티켓을 준수하여야 합니다. 특히 승강기를 “타거나 내릴 때 질서 지키기”, “어린이와 노약자에게 우선 양보”, “뒤에 오는 탑승자를 위해 버튼 누르기” 등의 기본적인 에티켓을 지키면 본인은 물론 이용자 모두가 상쾌하게 이용할 수 있고 사고예방에도 도움이 됩니다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 1
          },
          {
            actRmks: '승강기를 타고 내릴 때는 질서를 지킵시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 2
          },
          {
            actRmks: '어린이와 노약자가 먼저 타고 내릴 수 있도록 양보합시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 3
          },
          {
            actRmks: '승강기 버튼으로 장난치지 말고 카 안에 휴지나 오물을 버리지 맙시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 4
          },
          {
            actRmks: '승강기 안에서 떠들지 말고 담배를 피우지 맙시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 5
          },
          {
            actRmks: '승강기 안에서 발을 구르는 등 충격을 주지 맙시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 6
          },
          {
            actRmks: '뒤에 타는 이용자를 위해 열림 버튼을 눌러줍시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 7
          },
          {
            actRmks: '정원이 초과되면 맨 나중에 탄 승객이 내립시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 안전 문화',
            subOrd: 8
          },
          {
            actRmks:
              '평소에 제대로 운행되던 승강기가 갑작스러운 정전이나 고장이 발생해 카 안에 갇히게 되는 경우가 있습니다. 이럴 땐 당황하고 조급한 마음으로 카 문을 열고 탈출을 시도하다가 승강로 아래로 추락하는 사고를 당할 수 있습니다. 이용 중이던 승강기가 갑작스러운 정전이나 고장을 일으켰을 때는 절대로 당황하지 말고 침착하게 카 내에 부착되어 있는 인터폰으로 관리사무실 등에 알려 전문가로부터 안전한 구조를 받아야 합니다.',
            contentsType: 1,
            mainOrd: 30,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014003,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 고장시 안전구조',
            subOrd: 1
          },
          {
            actRmks:
              '정전 등의 이유로 실내조명이 꺼지더라도 당황하지 말고 인터폰으로 연락하여야 합니다.',
            contentsType: 1,
            mainOrd: 30,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014003,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 고장시 안전구조',
            subOrd: 2
          },
          {
            actRmks: '임의로 판단하여 탈출을 시도하지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 30,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014003,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 고장시 안전구조',
            subOrd: 3
          },
          {
            actRmks: '구조의 요청으로 구출되는 경우 반드시 구출자의 지시에 따라야 합니다.',
            contentsType: 1,
            mainOrd: 30,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014003,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 고장시 안전구조',
            subOrd: 4
          },
          {
            actRmks: '카 문을 강제로 개방하지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 30,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014003,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '승강기 고장시 안전구조',
            subOrd: 5
          },
          {
            actRmks:
              '백화점, 대형 할인매장 등의 유통시설과 지하철역 등에 설치,운행되는 에스컬레이터와 수평보행기의 이용에 따른 안전사고가 갈수록 늘어나고 있습니다. 특히 어린이들이 안전수칙을 제대로 지키지 않아 많이 발생하는 에스컬레이터 사고는 발판의 가장자리에 옷자락이나 신체의 일부가 끼여서 일어나는 사례가 대부분 이지만, 수평보행기의 경우처럼 서로 교차하는 지점의 삼각부에 머리를 부딪쳐 부상을 입기도 합니다. 안전이용수칙을 지켜 사고를 예방합시다.',
            contentsType: 1,
            mainOrd: 40,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014004,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 안전 수칙',
            subOrd: 1
          },
          {
            actRmks: '옷이나 물건 등이 틈새에 끼이지 않도록 주의해야 합니다.',
            contentsType: 1,
            mainOrd: 40,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014004,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 안전 수칙',
            subOrd: 2
          },
          {
            actRmks: '핸드레일 밖으로 몸을 내밀지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 40,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014004,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 안전 수칙',
            subOrd: 3
          },
          {
            actRmks: '디딤판 위에 앉지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 40,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014004,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 안전 수칙',
            subOrd: 4
          },
          {
            actRmks: '어린이나 노약자는 보호자가 손을 잡고 타야 합니다.',
            contentsType: 1,
            mainOrd: 40,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014004,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 안전 수칙',
            subOrd: 5
          },
          {
            actRmks: '사고 발생시에는 비상정지버튼을 조작하여 작동을 멈추게 해야 합니다.',
            contentsType: 1,
            mainOrd: 40,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014004,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 안전 수칙',
            subOrd: 6
          },
          {
            actRmks: '엘리베이터 내에 부착된 유의사항을 지켜야 합니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 1
          },
          {
            actRmks: '탑승정원이나 적재하중의 초과는 고장과 사고의 원인이 될 수 있습니다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 2
          },
          {
            actRmks: '조작반의 인터폰, 비상정지스위치 등을 장난으로 조작하지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 3
          },
          {
            actRmks: '버튼을 불필요하게 누르거나 난폭하게 다루지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 4
          },
          {
            actRmks: '운행 중인 엘리베이터 내에서 뛰거나 심한 장난을 하지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 5
          },
          {
            actRmks: '엘리베이터 출입문을 흔들거나 손으로 밀지 말아야 하며 출입문에 기대지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 6
          },
          {
            actRmks: '엘리베이터 내에서는 담배를 피우지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 7
          },
          {
            actRmks:
              '어린이나 노약자는 될 수 있으면 보호자와 함께 탑승하도록 하고 애완동물은 안고 탑승합시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 8
          },
          {
            actRmks: '지정된 용도 이외에는 사용하지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 9
          },
          {
            actRmks: '출입문의 문턱 틈이나 문 사이에 이물질을 버리지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 10
          },
          {
            actRmks: '관리자의 입회·허락 없이 크거나 무거운 화물을 무단으로 싣지 맙시다.',
            contentsType: 1,
            mainOrd: 10,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005001,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 11
          },
          {
            actRmks:
              '정전으로 엘리베이터가 멈추거나 실내등이 꺼지면 침착하게 인터폰으로 연락합시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 1
          },
          {
            actRmks:
              '엘리베이터가 도중에 정지하면 마음대로 탈출하지 말고 인터폰으로 구조를 요청합시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 2
          },
          {
            actRmks: '비상환기구는 탈출구가 아니므로 열려고 하지 맙시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 3
          },
          {
            actRmks: '구조를 요청하여 구출되는 경우에는 반드시 구조요원의 안내에 따라야 합니다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 4
          },
          {
            actRmks: '굉음이 들리거나 진동이 있으면 인터폰으로 연락합시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 5
          },
          {
            actRmks: '출입문을 강제로 개방을 하지 맙시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 6
          },
          {
            actRmks: '화재가 난 때는 엘리베이터를 타지 마시고 반드시 계단을 이용하여 피난합시다.',
            contentsType: 1,
            mainOrd: 20,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014005,
            safetyCate4: 3014005002,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '엘리베이터 사고 예방은',
            subOrd: 7
          },
          {
            actRmks: '의복, 스카프 등이 틈새에 끼지 않도록 주의합시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 1
          },
          {
            actRmks: '핸드레일을 잡아주세요.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 2
          },
          {
            actRmks: '천천히 타도록 하고, 황색 안전선 안쪽에 타야 합니다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 3
          },
          {
            actRmks: '가장자리에는 발이 닿지 않도록 합시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 4
          },
          {
            actRmks:
              '유아와 애완동물은 안고 타야 하며 어린이나 노약자는 보호자의 손을 꼭 잡고 타야 합니다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 5
          },
          {
            actRmks: '주행방향을 거슬러 타거나 장난을 하지 맙시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 6
          },
          {
            actRmks: '어린이가 에스컬레이터 위에서 놀지 않도록 지도합시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 7
          },
          {
            actRmks: '계단에 앉거나 맨발로 타지 맙시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 8
          },
          {
            actRmks: '동전, 열쇠 등을 떨어뜨리지 않도록 가방이나 주머니에 넣도록 합시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 9
          },
          {
            actRmks: '유모차 등은 접어서 들고 타야 합니다(수평보행기 제외).',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 10
          },
          {
            actRmks: '화물을 싣거나 계단에 놓지 맙시다(수평보행기 제외).',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 11
          },
          {
            actRmks: '담배를 피우거나 꽁초, 쓰레기 등을 버리지 맙시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 12
          },
          {
            actRmks: '비상정지 버튼을 함부로 누르지 맙시다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 13
          },
          {
            actRmks: '핸드레일 밖으로 머리나 팔을 내밀지 말아야 합니다.',
            contentsType: 1,
            mainOrd: 60,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCate3: 3014006,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            safetyCateNm3: '에스컬레이터 및 무빙업 안전사고 예방은',
            subOrd: 14
          },
          {
            actRmks: '승강기 사고 발생시 대처 요령',
            contentsType: 3,
            contentsUrl: 'rtsp://125.60.33.158/Low/Low/Elevator1.mp4',
            mainOrd: 500,
            platformId: 1,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            subOrd: 1
          },
          {
            actRmks: '승강기 사고 발생시 대처 요령',
            contentsType: 4,
            contentsUrl:
              'http://125.60.33.158:1935/Caption/Caption/mp4:Elevator1_Caption.mp4/playlist.m3u8',
            mainOrd: 500,
            platformId: 2,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            subOrd: 1
          },
          {
            actRmks: '승강기 사고 발생시 대처 요령',
            contentsType: 4,
            contentsUrl: 'rtsp://125.60.33.158/Caption/Caption/Elevator1_Caption.mp4',
            mainOrd: 500,
            platformId: 1,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            subOrd: 1
          },
          {
            actRmks: '승강기 사고 발생시 대처 요령',
            contentsType: 3,
            contentsUrl: 'http://125.60.33.158:1935/Low/Low/mp4:Elevator1.mp4/playlist.m3u8',
            mainOrd: 500,
            platformId: 2,
            safetyCate1: 3,
            safetyCate2: 3014,
            safetyCateNm1: '생활안전',
            safetyCateNm2: '승강기 안전사고',
            subOrd: 1
          }
        ]
      },
      numOfRows: 10,
      pageNo: 1,
      totalCount: 65
    }
  }
}
export default tranportMachineAcc
